language: android
jdk: oraclejdk8
script: "./gradlew build"
android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23
